### ISSUE TITLE
CSS Media Query output unpredictable when using breakpoints

### ISSUE THREAD

**Issue by slvvn** [jpudysz/react-native-unistyles#792]
### What happened?

Hi there!

First of all, I've been using the CSS output parser of Unistyles heavily over the last weeks, and I notice it becoming more stable over time, so nice work 🙌.

I still have this issue that the CSS output is not what I would expect from it, and that makes it difficult to debug, but I think I found a reproduceable example.

### Steps to Reproduce

The issue is that when defining different values for different breakpoints (not using `mq`), the output in these scenario's has unpredictable CSS behaviour. For example:

For this style applied to a `View`:
```ts
const stylesheet = StyleSheet.create(() => {
  return {
    container: {
      borderColor: {
        xs: "darkblue",
        md: "darkgreen",
      },
      backgroundColor: {
        xs: "lightblue",
        md: "lightgreen",
      },
    },
  };
});
```

the output is:
```css
@media (min-width: 0px) and (max-width: 767px) {
  .unistyles_1k4mls5uvjd {
    border-color:darkblue;
    background-color:lightblue;
  }
}
@media (min-width: 768px) {
  .unistyles_1k4mls5uvjd {
    border-color:darkgreen;
    background-color:lightgreen;
  }
}
```
(which is what I would expect, from width `0` the color is blue and from `768px` onward the color is green)

However when adding one more breakpoint to only one style property into the mix, like this:
```ts
const stylesheet = StyleSheet.create(() => {
  return {
    container: {
      borderColor: {
        xs: "darkblue",
        md: "darkgreen",
      },
      backgroundColor: {
        xs: "lightblue",
        md: "lightgreen",
        lg: "lightyellow", // <-- added
      },
    },
  };
});
```

The output becomes:
```css
.unistyles_wzch88muio {
  padding:32px;
  border-width:4px;
}
@media (min-width: 0px) and (max-width: 767px) {
  .unistyles_wzch88muio {
    border-color:darkblue;
    background-color:lightblue;
  }
}
@media (min-width: 768px) and (max-width: 1023px) {
  .unistyles_wzch88muio {
    border-color:darkgreen;
    background-color:lightgreen;
  }
}
@media (min-width: 1024px) {
  .unistyles_wzch88muio {
    background-color:lightyellow;
  }
}
```
(notice the second media query becoming a `min-width` `max-width` combination, and the the new media query only having the `background-color`)

This results in the border-color not being green anymore from `1023px` onwards.

### Snack or Repository Link (Optional)

https://github.com/slvvn/unistyles-v3-repro/tree/repro/css-media-queries

### Unistyles Version

3.0.0-preview.4

### React Native Version

0.79.2

### Platforms

Web

### Expo

Yes

### Additional information

- [x] I use recommended version of `react-native-nitro-modules` [compatibility table](https://github.com/jpudysz/react-native-unistyles?tab=readme-ov-file#installation)
- [x] I've searched for [similar issues in this repository](https://github.com/jpudysz/react-native-unistyles/issues) and found none
- [x] I double-checked that my issue was not covered in [documentation](https://unistyl.es/v3/guides/why-my-view-doesnt-update)
